### ISSUE TITLE
Tuning

### ISSUE THREAD

**Issue by suri97** [shivangchopra11/DigitRecognition#1]
Try a better architecture -> 
Dense(512, relu) or Dense(128,relu)
Dense(64, relu)
Dropout(0.2)
Dense(10, softmax)

**Comment by shivangchopra11** [comment]
Sir I'll be updating it with a CNN once you clear all my doubts. Please give me an appointment for the same...

**Comment by suri97** [comment]
Ye nalla tere doubts kaha se clear kr paega 😪

**Comment by shivangchopra11** [comment]
Itni pro log ho sab sikha dia ab itne modest ban ke kya fayda guruji....    _/ \\\_
